# Generated by Django 5.1.6 on 2025-03-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="state",
            new_name="postcode",
        ),
    ]
