# Generated by Django 5.1.6 on 2025-03-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="product_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
