# Generated by Django 5.1.6 on 2025-03-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderproduct_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="state",
            new_name="postcode",
        ),
    ]
